services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
